/*
 * FileDialog is a dialog to edit or add new file to the selected pack.
 */

package org.biz.izpack.GUI;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.biz.izpack.models.packs.FileModel;
import org.biz.izpack.models.packs.PackModel;

/**
 *
 * @author basar
 */

public class FileDialog extends javax.swing.JDialog {
    
    private String _fileName;
    
    private FileModel _file;
    
    private PackModel _parentNode;
    
    private int _selectedFileIndex;
    
    private int _parentPackIndex;

    /**
     * Creates new form FileDialog
     */
    public FileDialog(java.awt.Frame parent, PackModel parentNode, FileModel selected, int fileIndex, int packIndex) {
        super(parent, true);
        initComponents();
        
        // Init vars
        this._parentNode = parentNode;
        this._selectedFileIndex = fileIndex;
        this._parentPackIndex = packIndex;
        if (selected != null) {
            this._file = selected;
        } else {
            this._file = new FileModel();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_source = new javax.swing.JLabel();
        lbl_targetDir = new javax.swing.JLabel();
        tf_targetDir = new javax.swing.JTextField();
        btn_ok = new javax.swing.JButton();
        btn_browse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_source.setText("Source : ");

        lbl_targetDir.setText("Target Dir : ");

        tf_targetDir.setText("Target Dir");
        tf_targetDir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_targetDir_focuslost(evt);
            }
        });

        btn_ok.setText("OK");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ok_pressed(evt);
            }
        });

        btn_browse.setText("Browse");
        btn_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_browse_pressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_targetDir)
                    .addComponent(lbl_source))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ok)
                    .addComponent(tf_targetDir, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_browse))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_source)
                    .addComponent(btn_browse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_targetDir)
                    .addComponent(tf_targetDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ok)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_targetDir_focuslost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_targetDir_focuslost
        // Textfield validation
        if (tf_targetDir.getText().isEmpty() == true) {
            tf_targetDir.setText("Target Dir");
            JOptionPane.showMessageDialog(null, "Target Dir cannot be empty.", "Target Dir is empty!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tf_targetDir_focuslost

    private void btn_ok_pressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ok_pressed
        // Validation for browse button
        if (_fileName == null){
            return;
        }
        
        // Force to textfield to validation
        tf_targetDir.requestFocus(false);
        
        // Set vars
        _file.setSource(_fileName); 
        _file.setTargetDir(tf_targetDir.getText());
        
        // Remove old value from list (if exists) and add
        // new one to the selected index (if exists)
        if (_selectedFileIndex == -1) {
            _parentNode.getFiles().remove(_file);
            _parentNode.getFiles().add(_file);
        } else {
            _parentNode.getFiles().remove(_file);
            _parentNode.getFiles().add(_selectedFileIndex,_file);
        }
        
        // Insert parent node
        if (_parentPackIndex == -1) {
            MainFrame.installation.getPacksModel().getPacks().remove(_parentNode);
            MainFrame.installation.getPacksModel().getPacks().add(_parentNode);
        } else {
            MainFrame.installation.getPacksModel().getPacks().remove(_parentNode);
            MainFrame.installation.getPacksModel().getPacks().add(_parentPackIndex,_parentNode);
        }
        // Hide dialog
        this.setVisible(false);
    }//GEN-LAST:event_btn_ok_pressed

    private void btn_browse_pressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_browse_pressed
        // File node filechooser for src chosing
        JFileChooser chooser = new JFileChooser();
        
        // It is allowed to set dir or file
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            _fileName = chooser.getSelectedFile().getAbsolutePath();
        }
    }//GEN-LAST:event_btn_browse_pressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_browse;
    private javax.swing.JButton btn_ok;
    private javax.swing.JLabel lbl_source;
    private javax.swing.JLabel lbl_targetDir;
    private javax.swing.JTextField tf_targetDir;
    // End of variables declaration//GEN-END:variables
}
