/*
 * JarDialog is a dialog to edit or add new jar entity.
 */

package org.biz.izpack.GUI;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.biz.izpack.models.jars.JarModel;

/**
 *
 * @author basar
 */

public class JarDialog extends javax.swing.JDialog {
    
    private String _fileName;
    
    private JarModel _jar;
    
    private int _selectedIndex;

    /**
     * Creates new form JarDialog
     */
    public JarDialog(java.awt.Frame parent, JarModel selected, int selectedIndex) {
        super(parent, true);
        initComponents();
        
        // Set private vars
        if (selected != null) {
            this._jar = selected;
            this._selectedIndex = selectedIndex;
        } else {
            this._jar = new JarModel();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_src = new javax.swing.JLabel();
        lbl_stage = new javax.swing.JLabel();
        btn_ok = new javax.swing.JButton();
        cb_stage = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_src.setText("Source : ");

        lbl_stage.setText("Stage : ");

        btn_ok.setText("OK");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ok_pressed(evt);
            }
        });

        cb_stage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "install" }));

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_browse_pressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_src)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 54, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_stage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_stage, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btn_ok)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_src)
                    .addComponent(jButton1))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_stage)
                    .addComponent(cb_stage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btn_ok)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ok_pressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ok_pressed
        // File validation
        if (_fileName == null) {
            JOptionPane.showMessageDialog(null, "File cannot be empty.", "File is not setted!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Set vars
        _jar.setSource(_fileName);
        _jar.setStage((String)cb_stage.getSelectedItem());
        
        // Add or Update entity
        MainFrame.installation.getJarsModel().remove(_jar);
        if (_selectedIndex == -1) {
            MainFrame.installation.getJarsModel().add(_jar);
        } else {
            MainFrame.installation.getJarsModel().add(_selectedIndex, _jar);
        }
        
        // Hide dialog
        this.setVisible(false);
    }//GEN-LAST:event_btn_ok_pressed

    private void btn_browse_pressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_browse_pressed
        // File chooser usage, not filtered
        JFileChooser chooser = new JFileChooser();
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            _fileName = chooser.getSelectedFile().getAbsolutePath();
        }
    }//GEN-LAST:event_btn_browse_pressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ok;
    private javax.swing.JComboBox cb_stage;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbl_src;
    private javax.swing.JLabel lbl_stage;
    // End of variables declaration//GEN-END:variables
}
