/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.biz.izpack.GUI;

import javax.swing.JOptionPane;
import org.biz.izpack.models.information.AuthorModel;
import org.biz.izpack.models.panels.PanelModel;

/**
 *
 * @author basar
 */
public class PanelDialog extends javax.swing.JDialog {
    
    private PanelModel _panel;
    
    private int _selectedIndex;

    /**
     * Creates new form PanelDialog
     */
    public PanelDialog(java.awt.Frame parent, PanelModel selected, int selectedIndex) {
        super(parent, true);
        initComponents();
        this._selectedIndex = selectedIndex;
        if (selected != null) {
            this._panel = selected;
        } else {
            this._panel = new PanelModel();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_name = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        btn_ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_name.setText("Panel Name : ");

        tf_name.setText("TestPanel");
        tf_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_name_focuslost(evt);
            }
        });

        btn_ok.setText("OK");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ok_pressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_name, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btn_ok)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name)
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btn_ok)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ok_pressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ok_pressed
        tf_name.requestFocus(false);
        _panel.setClassName(tf_name.getText());
        if (_selectedIndex == -1) {
            MainFrame.avilablePanels.remove(_panel);
            MainFrame.avilablePanels.add(_panel);
        } else {
            MainFrame.avilablePanels.remove(_panel);
            MainFrame.avilablePanels.add(_selectedIndex, _panel);
        }
        this.setVisible(false);
        
    }//GEN-LAST:event_btn_ok_pressed

    private void tf_name_focuslost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_name_focuslost
        if (tf_name.getText().isEmpty() == true) {
            tf_name.setText("TestPanel");
            JOptionPane.showMessageDialog(null, "Panel Name cannot be empty.", "Panel Name is empty!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tf_name_focuslost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ok;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JTextField tf_name;
    // End of variables declaration//GEN-END:variables
}
