/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.biz.izpack;

import javax.swing.JOptionPane;

/**
 *
 * @author basar
 */
public class AuthorDialog extends javax.swing.JDialog {
    
    private Author _author;

    /**
     * Creates new form AuthorDialog
     */
    public AuthorDialog(java.awt.Frame parent, Author selected) {
        super(parent, true);
        initComponents();
        if (selected != null) {
            this._author = selected;
        } else {
            this._author = new Author();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_authorName = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        tf_authorName = new javax.swing.JTextField();
        tf_email = new javax.swing.JTextField();
        btn_ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_authorName.setText("Author Name : ");

        lbl_email.setText("Email : ");

        tf_authorName.setText("Kade");
        tf_authorName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_authorName_focuslost(evt);
            }
        });

        tf_email.setText("destek@kade.com.tr");
        tf_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_email_focuslost(evt);
            }
        });

        btn_ok.setText("OK");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ok_pressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_authorName)
                        .addGap(18, 18, 18)
                        .addComponent(tf_authorName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_email)
                        .addGap(57, 57, 57)
                        .addComponent(tf_email, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_ok)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_authorName)
                    .addComponent(tf_authorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_email)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ok)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ok_pressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ok_pressed
        tf_authorName.requestFocus(false);
        tf_email.requestFocus(false);
        _author.setName(tf_authorName.getText());
        if (!_author.setEmail(tf_email.getText())) {
            tf_email.setText("destek@kade.com.tr");
            JOptionPane.showMessageDialog(null, "Please enter a valid email.", "Email is not valid!", JOptionPane.ERROR_MESSAGE);
            return;
        } 
        MainFrame.installation.getInfo().addAuthor(_author);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ok_pressed

    private void tf_authorName_focuslost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_authorName_focuslost
        if (tf_authorName.getText().isEmpty() == true) {
            tf_authorName.setText("Kade");
            JOptionPane.showMessageDialog(null, "Author Name cannot be empty.", "Author Name is empty!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tf_authorName_focuslost

    private void tf_email_focuslost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_email_focuslost
        if (tf_email.getText().isEmpty() == true) {
            tf_email.setText("destek@kade.com.tr");
            JOptionPane.showMessageDialog(null, "Email cannot be empty.", "Email is empty!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tf_email_focuslost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ok;
    private javax.swing.JLabel lbl_authorName;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JTextField tf_authorName;
    private javax.swing.JTextField tf_email;
    // End of variables declaration//GEN-END:variables
}
